const Sdata=[
    { imgsrc:"https://wallpapercave.com/wp/wp4056410.jpg",
      title:"A Netflix Original series",
      sname:"DARK",
      link:"https://www.netflix.com/in/title/80990668?source=35",
},
{     imgsrc:"https://wallpapercave.com/wp/wp4056410.jpg",
      title:"A Netflix Original series",
      sname:"EXTRA CURRICULAM",
      link:"https://www.netflix.com/in/title/80990668?source=35",
},
{     imgsrc:"https://wallpapercave.com/wp/wp4056410.jpg",
      title:"A Netflix Original series",
      sname:"SACRED GAMES",
      link:"https://www.netflix.com/in/title/80990668?source=35",
},
{     imgsrc:"https://wallpapercave.com/wp/wp4056410.jpg",
      title:"A Netflix Original series",
      sname:"SACRED GAMES",
      link:"https://www.netflix.com/in/title/80990668?source=35",
},
{     imgsrc:"https://wallpapercave.com/wp/wp4056410.jpg",
      title:"A Netflix Original series",
      sname:"SACRED GAMES",
      link:"https://www.netflix.com/in/title/80990668?source=35",
},
];

export default Sdata;